### ISSUE TITLE
Free formal tools

### ISSUE THREAD

**Issue by Contental** [ben-marshall/awesome-open-hardware-verification#3]
Daniel Kroening and his team at Oxford Uni have developed a formal verif tool.  I think it has support from the EU somehow.

From my experience the engine looks like it's probably very good, but the UI is basic and I have hit some issues compiling SV occasionally,  It's the best free formal tool I've seen though.

Enhanced Bounded Model Checker, includes unbounded!
http://www.cprover.org/ebmc/

**Comment by ben-marshall** [comment]
Hi, thanks a lot for this!

I knew this tool existed but had forgotten the name and so couldn't find it again. I'll add it shortly.
